//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_an_Winform
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapHang
    {
        public string MaPN { get; set; }
        public System.DateTime NgayTaoPN { get; set; }
        public string MaNV { get; set; }
        public string MaSP { get; set; }
        public string MaLoaiSP { get; set; }
        public string MaNhaSX { get; set; }
        public int SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string MaNhaCC { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
